import { Hanuman, Italianno } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const italianno = Italianno({
  variable: '--font-italianno',
  subsets: ['latin'],
  weight: ['400'],
});

const hanuman = Hanuman({
  variable: "--font-hanuman",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Mangia Mogo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${hanuman.variable} ${italianno.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}